#!/bin/bash
gcc -g -O3 -c -I lib/LTSmin/include/ -I autogenerated -std=c99 -fPIC autogenerated/dlopen-impl.c -o autogenerated/dlopen-impl.o
gcc -w -g -c -I lib/LTSmin/include -I autogenerated -std=c99 -fPIC autogenerated/autogeneratedfile.c -o autogenerated/autogeneratedfile.o

gcc -shared  -o autogenerated/sharedfile.so -undefined dynamic_lookup autogenerated/dlopen-impl.o autogenerated/autogeneratedfile.o

lib/ltsmin.osx64/pins2lts-seq --state=table --invariant="! goal" --when autogenerated/sharedfile.so
#lib/ltsmin.osx64/pins2lts-mc --state=table --invariant="! goal" --when autogenerated/sharedfile.so
#lib/ltsmin.osx64/ltsmin-printtrace solution.gcf


#Setting for query: --invariant="! goal" 
#Setting for tracelog: --trace=solution.gcf
#Setting for deadlock: --deadlock
#Setting for benchmark-test: --when
#Setting for use of table instead of tree: --state=table

#Command for LTSmin multi-core: pins2lts-mc
#Command for LTSmin singlecore-core: pins2lts-seq

#Pretty Print tracelog: ltsmin-printtrace solution.gcf