#!/bin/bash
# This script calls LTSmin with the created successor generator shared object file.

# *************** LTSMIN SETTINGS ************************
# Setting for query: --invariant="! goal" 
# Setting for tracelog: --trace=solution.gcf
# Setting for deadlock: --deadlock
# Setting for benchmark-test: --when
# Setting for use of table instead of tree: --state=table

# Pretty Print tracelog: ltsmin-printtrace solution.gcf
# ********************************************************

# Expect -mc to run ltsmin multicore (default sequential)
LTSMINTYPE=$1

if [[ $OSTYPE == linux* ]]
then
    LTSMINPATH="lib/LTSmin/bin/"
elif [[ $OSTYPE == darwin* ]]
then
    LTSMINPATH="lib/ltsmin.osx64/"
    CFLAGS="-undefined dynamic_lookup"
fi

gcc -O3 -c -I lib/LTSmin/include/ -I autogenerated -std=c99 -fPIC autogenerated/dlopen-impl.c -o autogenerated/dlopen-impl.o
gcc -w -c -I lib/LTSmin/include -I autogenerated -std=c99 -fPIC autogenerated/autogeneratedfile.c -o autogenerated/autogeneratedfile.o
gcc -shared -o autogenerated/sharedfile.so $CFLAGS autogenerated/dlopen-impl.o autogenerated/autogeneratedfile.o

if [[ $LTSMINTYPE == "-mc" ]]
then
    ${LTSMINPATH}pins2lts-mc --state=table --invariant="! goal" --trace=solution.gcf --when autogenerated/sharedfile.so 
else
    ${LTSMINPATH}pins2lts-seq --state=table --invariant="! goal" --trace=solution.gcf --when autogenerated/sharedfile.so 
fi
